
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace WeatherMonitor.GUI
{
    using Microsoft.Extensions.Configuration;
    using Terminal.Gui;
    using WeatherMonitor.Extensions;
    using WeatherMonitor.Models;

    public partial class DataPointsWindow
    {

        private readonly IConfiguration _config;
        private readonly IAPIClient _api;
        private List<string> allpoints;
        private readonly Station _station;
        private readonly IDataProvider _provider;
        public DataPointsWindow(IAPIClient api, IConfiguration config, Station station, IDataProvider provider)
        {
            _config = config;
            _api = api;
            InitializeComponent();
            lvdatapoints.SelectedItemChanged += Lvdatapoints_SelectedItemChanged;
            _station = station;
            lblTitle.Text = $"Please select a data point for the {_station.Name} ({_station.ID})";
            _provider = provider;
        }

        private async void Lvdatapoints_SelectedItemChanged(ListViewItemEventArgs obj)
        {
            var selectedDataPoint = allpoints[obj.Item];
            var table = await _provider.GetDataTable(_station.ID, selectedDataPoint);
            MainWindow win = new MainWindow(_api, _config, _provider);
            this.LoadWindow(win, () => win.Refresh(table, _station,string.Empty,string.Empty));
        }

        public void RefreshList(List<string> points)
        {
            allpoints = points;
            var list = points.Select((p, idx) => $"{idx}. {p}").ToList();
            lvdatapoints.SetSource(list);
        }
    }
}
