
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace WeatherMonitor.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class DataPointsWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.Label lblHeader;
        
        private Terminal.Gui.Label lblTitle;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.ListView lvdatapoints;
        
        private void InitializeComponent() {
            this.lvdatapoints = new Terminal.Gui.ListView();
            this.frameView = new Terminal.Gui.FrameView();
            this.lblTitle = new Terminal.Gui.Label();
            this.lblHeader = new Terminal.Gui.Label();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.lblHeader.Width = Dim.Percent(100f);
            this.lblHeader.Height = 1;
            this.lblHeader.X = 0;
            this.lblHeader.Y = 0;
            this.lblHeader.Visible = true;
            this.lblHeader.ColorScheme = this.blueOnBlack;
            this.lblHeader.Data = "lblHeader";
            this.lblHeader.Text = "========== AVAILABLE DATA POINTS ==========";
            this.lblHeader.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.lblHeader);
            this.lblTitle.Width = Dim.Percent(100f);
            this.lblTitle.Height = 1;
            this.lblTitle.X = 1;
            this.lblTitle.Y = 1;
            this.lblTitle.Visible = true;
            this.lblTitle.ColorScheme = this.redOnBlack;
            this.lblTitle.Data = "lblTitle";
            this.lblTitle.Text = "Test data";
            this.lblTitle.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblTitle);
            this.frameView.Width = Dim.Percent(100f);
            this.frameView.Height = Dim.Percent(95f);
            this.frameView.X = 0;
            this.frameView.Y = 3;
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "";
            this.Add(this.frameView);
            this.lvdatapoints.Width = Dim.Percent(100f);
            this.lvdatapoints.Height = Dim.Percent(100f);
            this.lvdatapoints.X = 0;
            this.lvdatapoints.Y = 0;
            this.lvdatapoints.Visible = true;
            this.lvdatapoints.ColorScheme = this.blueOnBlack;
            this.lvdatapoints.Data = "lvdatapoints";
            this.lvdatapoints.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lvdatapoints.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.lvdatapoints.AllowsMarking = false;
            this.lvdatapoints.AllowsMultipleSelection = false;
            this.frameView.Add(this.lvdatapoints);
        }
    }
}
