
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace WeatherMonitor.GUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme statusBarColor2;
        
        private Terminal.Gui.ColorScheme titleColor2;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme tableColor;
        
        private Terminal.Gui.ColorScheme messagecolor;
        
        private Terminal.Gui.ColorScheme refreshbutton;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Button btnstation;
        
        private Terminal.Gui.Button btndp;
        
        private Terminal.Gui.Button btnrefresh;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TableView tblData;
        
        private Terminal.Gui.StatusBar statusBar;
        
        private Terminal.Gui.StatusItem lblStatus;
        
        private Terminal.Gui.StatusItem lblStation;
        
        private Terminal.Gui.StatusItem lblWmo;
        
        private Terminal.Gui.StatusItem pageDownPageUp;
        
        private Terminal.Gui.StatusItem avgTemp;
        
        private Terminal.Gui.StatusItem statmsg;
        
        private void InitializeComponent() {
            this.statusBar = new Terminal.Gui.StatusBar();
            this.tblData = new Terminal.Gui.TableView();
            this.label2 = new Terminal.Gui.Label();
            this.btnrefresh = new Terminal.Gui.Button();
            this.btndp = new Terminal.Gui.Button();
            this.btnstation = new Terminal.Gui.Button();
            this.label = new Terminal.Gui.Label();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.statusBarColor2 = new Terminal.Gui.ColorScheme();
            this.statusBarColor2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.statusBarColor2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.statusBarColor2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.statusBarColor2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.statusBarColor2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.titleColor2 = new Terminal.Gui.ColorScheme();
            this.titleColor2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.DarkGray);
            this.titleColor2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.titleColor2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.titleColor2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.titleColor2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.tableColor = new Terminal.Gui.ColorScheme();
            this.tableColor.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.BrightGreen);
            this.tableColor.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.tableColor.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.tableColor.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.tableColor.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.messagecolor = new Terminal.Gui.ColorScheme();
            this.messagecolor.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.DarkGray);
            this.messagecolor.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.messagecolor.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.messagecolor.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.messagecolor.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.refreshbutton = new Terminal.Gui.ColorScheme();
            this.refreshbutton.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightMagenta, Terminal.Gui.Color.Black);
            this.refreshbutton.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Magenta, Terminal.Gui.Color.Black);
            this.refreshbutton.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Magenta, Terminal.Gui.Color.Black);
            this.refreshbutton.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Magenta, Terminal.Gui.Color.Black);
            this.refreshbutton.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.label.Width = Dim.Percent(100f);
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.ColorScheme = this.titleColor2;
            this.label.Data = "label";
            this.label.Text = "========== WEATHER MONITOR ==========";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.label);
            this.btnstation.Width = 23;
            this.btnstation.Height = 1;
            this.btnstation.X = 1;
            this.btnstation.Y = 2;
            this.btnstation.Visible = true;
            this.btnstation.ColorScheme = this.redOnBlack;
            this.btnstation.Data = "btnstation";
            this.btnstation.Text = "Change Station [F4]";
            this.btnstation.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnstation.IsDefault = false;
            this.Add(this.btnstation);
            this.btndp.Width = 28;
            this.btndp.Height = 1;
            this.btndp.X = 23;
            this.btndp.Y = 2;
            this.btndp.Visible = true;
            this.btndp.ColorScheme = this.greenOnBlack;
            this.btndp.Data = "btndp";
            this.btndp.Text = "Select a data point [F6]";
            this.btndp.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btndp.IsDefault = false;
            this.Add(this.btndp);
            this.btnrefresh.Width = 16;
            this.btnrefresh.Height = 1;
            this.btnrefresh.X = 53;
            this.btnrefresh.Y = 2;
            this.btnrefresh.Visible = true;
            this.btnrefresh.ColorScheme = this.refreshbutton;
            this.btnrefresh.Data = "btnrefresh";
            this.btnrefresh.Text = "Refresh [F5]";
            this.btnrefresh.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnrefresh.IsDefault = false;
            this.Add(this.btnrefresh);
            this.label2.Width = 1;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 4;
            this.label2.Visible = true;
            this.label2.ColorScheme = this.messagecolor;
            this.label2.Data = "label2";
            this.label2.Text = "Scroll with your mouse or use Page Up/Page Down keys to navigate the table.";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.tblData.Width = Dim.Percent(100f);
            this.tblData.Height = Dim.Percent(90f);
            this.tblData.X = 0;
            this.tblData.Y = 5;
            this.tblData.Visible = true;
            this.tblData.ColorScheme = this.blueOnBlack;
            this.tblData.Data = "tblData";
            this.tblData.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tblData.FullRowSelect = false;
            this.tblData.Style.AlwaysShowHeaders = false;
            this.tblData.Style.ExpandLastColumn = true;
            this.tblData.Style.InvertSelectedCellFirstCharacter = false;
            this.tblData.Style.ShowHorizontalHeaderOverline = true;
            this.tblData.Style.ShowHorizontalHeaderUnderline = true;
            this.tblData.Style.ShowVerticalCellLines = true;
            this.tblData.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tblDataTable;
            tblDataTable = new System.Data.DataTable();
            System.Data.DataColumn tblDataTableDateTime;
            tblDataTableDateTime = new System.Data.DataColumn();
            tblDataTableDateTime.ColumnName = "Date/Time";
            tblDataTable.Columns.Add(tblDataTableDateTime);
            System.Data.DataColumn tblDataTableLat;
            tblDataTableLat = new System.Data.DataColumn();
            tblDataTableLat.ColumnName = "Lat";
            tblDataTable.Columns.Add(tblDataTableLat);
            System.Data.DataColumn tblDataTableLon;
            tblDataTableLon = new System.Data.DataColumn();
            tblDataTableLon.ColumnName = "Lon";
            tblDataTable.Columns.Add(tblDataTableLon);
            System.Data.DataColumn tblDataTableTemp;
            tblDataTableTemp = new System.Data.DataColumn();
            tblDataTableTemp.ColumnName = "Temp";
            tblDataTable.Columns.Add(tblDataTableTemp);
            System.Data.DataColumn tblDataTableCloud;
            tblDataTableCloud = new System.Data.DataColumn();
            tblDataTableCloud.ColumnName = "Cloud";
            tblDataTable.Columns.Add(tblDataTableCloud);
            System.Data.DataColumn tblDataTableClBM;
            tblDataTableClBM = new System.Data.DataColumn();
            tblDataTableClBM.ColumnName = "Cl.BM";
            tblDataTable.Columns.Add(tblDataTableClBM);
            System.Data.DataColumn tblDataTableCloktas;
            tblDataTableCloktas = new System.Data.DataColumn();
            tblDataTableCloktas.ColumnName = "Cl.oktas";
            tblDataTable.Columns.Add(tblDataTableCloktas);
            System.Data.DataColumn tblDataTableClType;
            tblDataTableClType = new System.Data.DataColumn();
            tblDataTableClType.ColumnName = "Cl.Type";
            tblDataTable.Columns.Add(tblDataTableClType);
            System.Data.DataColumn tblDataTableClTyID;
            tblDataTableClTyID = new System.Data.DataColumn();
            tblDataTableClTyID.ColumnName = "Cl.TyID";
            tblDataTable.Columns.Add(tblDataTableClTyID);
            System.Data.DataColumn tblDataTableDeltaT;
            tblDataTableDeltaT = new System.Data.DataColumn();
            tblDataTableDeltaT.ColumnName = "DeltaT";
            tblDataTable.Columns.Add(tblDataTableDeltaT);
            System.Data.DataColumn tblDataTableDewPt;
            tblDataTableDewPt = new System.Data.DataColumn();
            tblDataTableDewPt.ColumnName = "DewPt";
            tblDataTable.Columns.Add(tblDataTableDewPt);
            System.Data.DataColumn tblDataTableGustKmh;
            tblDataTableGustKmh = new System.Data.DataColumn();
            tblDataTableGustKmh.ColumnName = "GustKmh";
            tblDataTable.Columns.Add(tblDataTableGustKmh);
            System.Data.DataColumn tblDataTableGustKt;
            tblDataTableGustKt = new System.Data.DataColumn();
            tblDataTableGustKt.ColumnName = "GustKt";
            tblDataTable.Columns.Add(tblDataTableGustKt);
            System.Data.DataColumn tblDataTablePressure;
            tblDataTablePressure = new System.Data.DataColumn();
            tblDataTablePressure.ColumnName = "Pressure";
            tblDataTable.Columns.Add(tblDataTablePressure);
            System.Data.DataColumn tblDataTablePresMsl;
            tblDataTablePresMsl = new System.Data.DataColumn();
            tblDataTablePresMsl.ColumnName = "PresMsl";
            tblDataTable.Columns.Add(tblDataTablePresMsl);
            System.Data.DataColumn tblDataTablePresQnh;
            tblDataTablePresQnh = new System.Data.DataColumn();
            tblDataTablePresQnh.ColumnName = "PresQnh";
            tblDataTable.Columns.Add(tblDataTablePresQnh);
            System.Data.DataColumn tblDataTablePresTrnd;
            tblDataTablePresTrnd = new System.Data.DataColumn();
            tblDataTablePresTrnd.ColumnName = "PresTrnd";
            tblDataTable.Columns.Add(tblDataTablePresTrnd);
            System.Data.DataColumn tblDataTableRainTrace;
            tblDataTableRainTrace = new System.Data.DataColumn();
            tblDataTableRainTrace.ColumnName = "RainTrace";
            tblDataTable.Columns.Add(tblDataTableRainTrace);
            System.Data.DataColumn tblDataTableRelHum;
            tblDataTableRelHum = new System.Data.DataColumn();
            tblDataTableRelHum.ColumnName = "Rel.Hum";
            tblDataTable.Columns.Add(tblDataTableRelHum);
            System.Data.DataColumn tblDataTableSeaState;
            tblDataTableSeaState = new System.Data.DataColumn();
            tblDataTableSeaState.ColumnName = "SeaState";
            tblDataTable.Columns.Add(tblDataTableSeaState);
            System.Data.DataColumn tblDataTableSwellDirWrd;
            tblDataTableSwellDirWrd = new System.Data.DataColumn();
            tblDataTableSwellDirWrd.ColumnName = "SwellDirWrd";
            tblDataTable.Columns.Add(tblDataTableSwellDirWrd);
            System.Data.DataColumn tblDataTableSwellH;
            tblDataTableSwellH = new System.Data.DataColumn();
            tblDataTableSwellH.ColumnName = "SwellH";
            tblDataTable.Columns.Add(tblDataTableSwellH);
            System.Data.DataColumn tblDataTableSwellP;
            tblDataTableSwellP = new System.Data.DataColumn();
            tblDataTableSwellP.ColumnName = "SwellP";
            tblDataTable.Columns.Add(tblDataTableSwellP);
            System.Data.DataColumn tblDataTableVisiKm;
            tblDataTableVisiKm = new System.Data.DataColumn();
            tblDataTableVisiKm.ColumnName = "Visi.Km";
            tblDataTable.Columns.Add(tblDataTableVisiKm);
            System.Data.DataColumn tblDataTableweather;
            tblDataTableweather = new System.Data.DataColumn();
            tblDataTableweather.ColumnName = "weather";
            tblDataTable.Columns.Add(tblDataTableweather);
            System.Data.DataColumn tblDataTableWindDir;
            tblDataTableWindDir = new System.Data.DataColumn();
            tblDataTableWindDir.ColumnName = "WindDir";
            tblDataTable.Columns.Add(tblDataTableWindDir);
            System.Data.DataColumn tblDataTableWindSpd;
            tblDataTableWindSpd = new System.Data.DataColumn();
            tblDataTableWindSpd.ColumnName = "WindSpd";
            tblDataTable.Columns.Add(tblDataTableWindSpd);
            System.Data.DataColumn tblDataTableWindspdkt;
            tblDataTableWindspdkt = new System.Data.DataColumn();
            tblDataTableWindspdkt.ColumnName = "Windspdkt";
            tblDataTable.Columns.Add(tblDataTableWindspdkt);
            this.tblData.Table = tblDataTable;
            this.Add(this.tblData);
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 1;
            this.statusBar.X = 0;
            this.statusBar.Y = Pos.AnchorEnd(1);
            this.statusBar.Visible = true;
            this.statusBar.ColorScheme = this.statusBarColor2;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "Adelaide Air Port";
            this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lblStatus = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(0u)), "lblStatus", null);
            this.lblStation = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(0u)), "lblStation", null);
            this.lblWmo = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(0u)), "lblWmo", null);
            this.pageDownPageUp = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(0u)), "Page Down/Page Up", null);
            this.avgTemp = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(0u)), "avgTemp", null);
            this.statmsg = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(0u)), "statmsg", null);
            this.statusBar.Items = new Terminal.Gui.StatusItem[] {
                    this.lblStatus,
                    this.lblStation,
                    this.lblWmo,
                    this.pageDownPageUp,
                    this.avgTemp,
                    this.statmsg};
            this.Add(this.statusBar);
        }
    }
}
