
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace WeatherMonitor.GUI
{
    using Microsoft.Extensions.Configuration;
    using System.Threading.Tasks;
    using Terminal.Gui;
    using WeatherMonitor.Extensions;
    using WeatherMonitor.Models;


    public partial class SplashWindow
    {

        private readonly IConfiguration _config;
        private readonly IAPIClient _api;
        private readonly Station _station;
        private IDataProvider _provider;
        public SplashWindow(IAPIClient api, IConfiguration config, Station station, IDataProvider provider)
        {
            InitializeComponent();
            _config = config;
            _api = api;
            _station = station;
            _provider = provider;
            this.KeyPress += SplashWindow_KeyPress;
            this.textView.KeyPress += SplashWindow_KeyPress;
            this.textView.VerticalTextAlignment = VerticalTextAlignment.Middle;
            this.textView.TextAlignment = TextAlignment.Centered;
        }

        private void SplashWindow_KeyPress(KeyEventEventArgs obj)
        {
            if (obj.KeyEvent.Key == Key.Enter)
            {
                initApp();
            }
        }

        public override async void OnLoaded()
        {
            await Task.Delay(1000 * 60);
            initApp();
        }

        private async void initApp()
        {
            this.textView.Text = "Starting. Please wait....";
            MainWindow wind = new MainWindow(_api, _config, _provider);
            var (tbl, msg, temp) = await _provider.GetDataTable(_station.ID);
            this.LoadWindow(wind, () => wind.Refresh(tbl, _station, msg, temp));
        }
    }
}
