
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace WeatherMonitor.GUI {
    using Microsoft.Extensions.Configuration;
    using System.Threading.Tasks;
    using Terminal.Gui;
    using WeatherMonitor.Extensions;
    using WeatherMonitor.Models;

    public partial class StationsWindow {
        
        private List<Station> allStations = new List<Station>();
        private readonly IConfiguration _config;
        private readonly IAPIClient _api;
        private readonly IDataProvider _provider;
        public StationsWindow(IAPIClient api, IConfiguration config, IDataProvider provider) {
            InitializeComponent();
            lvStations.SelectedItemChanged += LvStations_SelectedItemChanged;
            _config = config;
            _api = api;
            _provider = provider;
        }

        private async void LvStations_SelectedItemChanged(ListViewItemEventArgs obj)
        {
            var selectedStation = allStations[obj.Item];
            var (table,msg,temp) = await _provider.GetDataTable(selectedStation.ID);

            MainWindow win = new MainWindow(_api,_config, _provider);
            this.LoadWindow(win, () => win.Refresh(table, selectedStation,msg,temp));
        }

        public void RefreshList(List<Station> stations)
        {
            var list = stations.Select((s, i) => $"{i}. {s.ID}:{s.Name}").ToList();
            allStations = stations;
            lvStations.SetSource(list);
        }
    }
}
